# Generated by Django 3.2.7 on 2021-10-19 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgronetApp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_department',
        ),
        migrations.AlterField(
            model_name='departament',
            name='id_departament',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad', to='AgronetApp.city'),
        ),
    ]
