# Generated by Django 3.2.7 on 2021-10-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgronetApp', '0005_auto_20211018_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id_city',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
