# Generated by Django 3.2.7 on 2021-10-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgronetApp', '0006_alter_city_id_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex_user',
            field=models.CharField(choices=[('Femenino', 'Femenino')], max_length=10),
        ),
    ]
