# Generated by Django 3.2.7 on 2021-10-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgronetApp', '0007_alter_user_sex_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol_user',
            field=models.CharField(max_length=15, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex_user',
            field=models.CharField(max_length=10, verbose_name='Sexo'),
        ),
    ]
