# Generated by Django 3.2.7 on 2021-10-20 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgronetApp', '0008_auto_20211019_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='username_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
