# Generated by Django 3.2.7 on 2021-10-20 03:26

from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.expressions
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AgronetApp', '0009_alter_product_username_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='total_price_product',
            field=models.IntegerField(verbose_name=django.db.models.aggregates.Aggregate(django.db.models.aggregates.Sum(django.db.models.expressions.CombinedExpression(django.db.models.expressions.F(models.IntegerField()), '*', django.db.models.expressions.F(django.db.models.fields.IntegerField))))),
        ),
    ]
