# Generated by Django 3.2.7 on 2021-10-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgronetApp', '0011_remove_orderdetail_total_price_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='total_price_product',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='amount_order',
            field=models.IntegerField(null=True),
        ),
    ]
