# Generated by Django 3.2.7 on 2021-10-20 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgronetApp', '0012_auto_20211019_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='total_price_product',
            new_name='price_unit',
        ),
    ]
