# Generated by Django 3.2.7 on 2021-10-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgronetApp', '0013_rename_total_price_product_orderdetail_price_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='totals_price_product',
            field=models.IntegerField(null=True),
        ),
    ]
