# Generated by Django 3.2.7 on 2021-10-20 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgronetApp', '0014_orderdetail_totals_price_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='totals_price_product',
            new_name='total_price_product',
        ),
    ]
