from .productCreateView import ProductCreateView
from .productDetailView import ProductDetailView
from .orderDetailView import OrderDetailView
from .orderView import OrdersView
from .orderView import OrdersDetail
from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .userEditView import userEditView
from .cityView import CityViews
from .departamentView import DepartamentView
